sudo: python: command not found
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
2021-07-06 02:27:22.342865: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-06 02:27:22.342903: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-07-06 02:27:32.053293: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-07-06 02:27:32.055778: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-07-06 02:27:32.055819: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-31-236): /proc/driver/nvidia/version does not exist
2021-07-06 02:27:32.060442: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-06 02:27:32.201539: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-07-06 02:27:32.214954: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2400000000 Hz
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://172.31.31.236:5000/ (Press CTRL+C to quit)
WARNING:flask_cors.core:Unknown option passed to Flask-CORS: origin
WARNING:flask_cors.core:Unknown option passed to Flask-CORS: headers
2021-07-06 02:28:39.589379: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18524160 exceeds 10% of free system memory.
2021-07-06 02:28:42.137679: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18524160 exceeds 10% of free system memory.
2021-07-06 02:28:44.202334: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 18524160 exceeds 10% of free system memory.
INFO:werkzeug:51.211.30.17 - - [06/Jul/2021 02:28:45] "POST /upload HTTP/1.1" 200 -
WARNING:flask_cors.core:Unknown option passed to Flask-CORS: origin
WARNING:flask_cors.core:Unknown option passed to Flask-CORS: headers
INFO:werkzeug:51.211.30.17 - - [06/Jul/2021 02:28:56] "POST /upload HTTP/1.1" 200 -
WARNING:flask_cors.core:Unknown option passed to Flask-CORS: origin
WARNING:flask_cors.core:Unknown option passed to Flask-CORS: headers
INFO:werkzeug:51.211.30.17 - - [06/Jul/2021 02:29:07] "POST /upload HTTP/1.1" 200 -
